"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AppShell } from "../../../components/AppShell";
import { ErrorState, LoadingState, Panel, RiskBadge, formatMetric, labelFor } from "../../../components/ui";
import { ApiError, Wallet, btcScopeApi } from "../../../lib/api";

const behaviorKeys = ["tx_count", "sent_btc", "received_btc", "unique_counterparties", "rapid_tx_pairs_15m", "ip_count", "country_count", "asn_count"];
const graphKeys = ["in_degree", "out_degree", "neighbor_count", "fan_in_score", "fan_out_score", "chain_score"];

export default function WalletPage({ params }: { params: Promise<{ walletId: string }> }) {
  const [walletId, setWalletId] = useState("");
  const [wallet, setWallet] = useState<Wallet | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { params.then(({ walletId: value }) => { const id = decodeURIComponent(value).toUpperCase(); setWalletId(id); btcScopeApi.getWallet(id).then(setWallet).catch((cause: ApiError) => setError(cause.message)); }); }, [params]);
  return <AppShell>{error ? <ErrorState message={error} /> : !wallet ? <LoadingState label={`Loading wallet ${walletId || "…"}`} /> : <Investigation wallet={wallet} />}</AppShell>;
}

function Investigation({ wallet }: { wallet: Wallet }) {
  return <>
    <div className="investigation-heading"><div><div className="eyebrow">⌕ WALLET INVESTIGATION</div><h1>Wallet <code>{wallet.wallet_id}</code></h1><p>Behavioral, graph, and anomaly evidence from existing processed BTC-SCOPE outputs.</p></div><RiskBadge band={wallet.risk_band} /></div>
    <Panel className={`risk-hero ${wallet.risk_band.toLowerCase()}`}><div><div className="hero-score">{wallet.risk_score.toFixed(2)}</div><div><RiskBadge band={wallet.risk_band} /><p>Overall review-priority score on a 0–100 scale.</p></div></div><Link className="button" href={`/network?wallet=${wallet.wallet_id}`}>View in Network Graph →</Link></Panel>
    <section className="reason-section"><div className="section-title"><div><h2>Why this wallet was flagged</h2><p>Plain-language explanations generated by the current risk-scoring output.</p></div><code>{wallet.reasons.length} active signals</code></div><div className="reason-grid">{wallet.reasons.map((reason, index) => <article className="reason-card" key={reason}><span>{["ϟ", "⇄", "↗", "⌘", "◌"][index]}</span><h3>{reason}</h3><p>{reasonDescription(reason)}</p></article>)}</div></section>
    <div className="detail-grid"><MetricPanel title="Behavioral activity" subtitle="Transaction, timing, value, and observed network identity metrics." metrics={wallet.behavioral_metrics} keys={behaviorKeys} /><MetricPanel title="Graph structure" subtitle="Directed transaction-network metrics derived with NetworkX." metrics={wallet.graph_metrics} keys={graphKeys} /></div>
    <Panel><div className="section-title"><div><h2>Anomaly Scores</h2><p>Independent label-free signals used by the existing risk-scoring stage.</p></div></div><div className="anomaly-grid"><AnomalyScore title="Statistical baseline" value={wallet.anomaly_scores.statistical} suffix=" / 100" /><AnomalyScore title="Isolation Forest" value={wallet.anomaly_scores.isolation_forest} suffix=" anomaly score" /></div></Panel>
  </>;
}

function MetricPanel({ title, subtitle, metrics, keys }: { title: string; subtitle: string; metrics: Record<string, number>; keys: string[] }) {
  return <Panel><div className="section-title"><div><h2>{title}</h2><p>{subtitle}</p></div></div><dl className="metric-list">{keys.map((key) => <div key={key}><dt>{labelFor(key)}</dt><dd>{formatMetric(key, metrics[key])}</dd></div>)}</dl></Panel>;
}
function AnomalyScore({ title, value, suffix }: { title: string; value: number; suffix: string }) { return <div className="anomaly-score"><span>{title}</span><strong>{value.toFixed(4)}<small>{suffix}</small></strong></div>; }
function reasonDescription(reason: string) {
  if (reason.includes("rapid")) return "The processed timing features show more transactions close together than is typical in this synthetic dataset.";
  if (reason.includes("fan-in")) return "The graph contains unusually strong convergence of incoming transaction edges from distinct wallets.";
  if (reason.includes("fan-out")) return "The graph shows a comparatively broad outgoing dispersal pattern to distinct wallets.";
  if (reason.includes("volume")) return "Combined sent and received BTC volume ranks high relative to the monitored synthetic wallet population.";
  if (reason.includes("network identity")) return "The observed IP, country, and autonomous-system diversity ranks high in the behavioral features.";
  if (reason.includes("connectivity") || reason.includes("chain")) return "The directed transaction graph indicates an elevated structural relationship pattern.";
  return "This is a high-contributing signal in the deterministic, label-free risk-scoring model.";
}
